// Analyst Rolodex roster — this year's Mentorship Program members, extracted
// from their new-member form responses and written up in a professional,
// third-person voice (they/them, since pronouns weren't collected). Contact
// details (phone, personal and GT email) are intentionally NOT stored here.
// Photos are added later; until then each card shows an initials avatar.

export type RolodexMember = {
  id: string;
  slug: string;
  name: string;
  major: string;
  year: string;
  grad: string;
  gradYear: number;
  disciplines: string[];
  summary: string;
  experience: string;
};

export const MEMBERS: RolodexMember[] = [
  {
    id: "alexander-abdallah", slug: "alexander-abdallah", name: "Alexander Abdallah",
    major: "Business finance", year: "Junior", grad: "December 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Capital Markets", "Real Estate Investment Trusts (REITs)"],
    summary: "Alexander is strongly interested in pursuing real estate as a career and is still exploring their options while looking to learn more. They see the program as a valuable opportunity to develop their knowledge of the field and expand their professional network.",
    experience: "",
  },
  {
    id: "jared-abrahamian", slug: "jared-abrahamian", name: "Jared Abrahamian",
    major: "Masters of Architecture", year: "Full-Time Graduate Student", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Development", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Jared is primarily interested in gaining a deeper understanding of real estate development and connecting their architecture background to it. They hope the program will introduce how development works, what it looks like in practice, and the potential avenues available in the industry given their architecture experience.",
    experience: "Design Intern at Formations Studio; Business Consultant for Caterpillar; Design & Fabrication Intern at Georgia Tech.",
  },
  {
    id: "emmie-adams", slug: "emmie-adams", name: "Emmie Adams",
    major: "Construction Science and Management", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Brokerage/Investment Sales", "Acquisitions", "Capital Markets", "Development"],
    summary: "Emmie is exploring commercial real estate as a potential career path while building a foundation in development, construction, and finance. As a Construction Science and Management student, they are drawn to development and construction, and are also interested in acquisitions, capital markets, and brokerage/investment sales to deepen their understanding of the financial and transactional side of the industry. They hope the analyst program will strengthen their financial and analytical skills, particularly Excel-based modeling and underwriting, and that the case study project and alumni mentorship will help them apply new skills and explore the range of career paths in CRE.",
    experience: "",
  },
  {
    id: "andrew-alvarez", slug: "andrew-alvarez", name: "Andrew Alvarez",
    major: "Industrial Engineering", year: "Freshman", grad: "2029", gradYear: 2029,
    disciplines: ["Acquisitions", "Capital Markets", "Property Management"],
    summary: "Andrew is interested in acquisitions and property management, specifically in how decisions are made about which properties to purchase and how pricing is managed relative to surrounding properties to maximize a location's profitability. They see the analyst program as a way to learn networking, gain real-world experience in their areas of interest, and build relationships with program leaders to advance their career.",
    experience: "",
  },
  {
    id: "dhilan-anand", slug: "dhilan-anand", name: "Dhilan Anand",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Property Management"],
    summary: "Dhilan is interested in brokerage and investments, and is eager to learn how capital is deployed in acquisitions and large-scale projects. They see the Analyst Program as a mentorship opportunity to learn more and explore their interest in real estate.",
    experience: "Incoming intern with Project Destined through its Real Estate Private Equity Program.",
  },
  {
    id: "alvaro-saldarriaga-arcila", slug: "alvaro-saldarriaga-arcila", name: "Alvaro Saldarriaga Arcila",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 20209", gradYear: 0,
    disciplines: ["Development", "Construction", "Property Management", "Brokerage/Investment Sales"],
    summary: "Alvaro is interested in learning about the fundamentals and development side of real estate in order to build a strong foundation in the industry. They value hands-on experiences and activities that help them understand the concepts more deeply.",
    experience: "",
  },
  {
    id: "alexander-arredondo", slug: "alexander-arredondo", name: "Alexander Arredondo",
    major: "Mechanical Engineer", year: "Senior", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions"],
    summary: "Alexander is interested in learning how to acquire property as a source of passive income, with a focus on identifying plots of land or properties that would deliver a strong return on investment.",
    experience: "Project Engineer, developing technical solutions for construction sites and implementing safety standards.",
  },
  {
    id: "andrew-best", slug: "andrew-best", name: "Andrew Best",
    major: "Business Administration, Finance", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    summary: "Andrew is interested in learning about all aspects of real estate to discover what appeals to them most. They see the Analyst Program as a foundation for entering real estate finance and a valuable resource for future networking and career development.",
    experience: "Incoming Finance Intern at Pratt Industries.",
  },
  {
    id: "benjamin-blakeley", slug: "benjamin-blakeley", name: "Benjamin Blakeley",
    major: "Business Administration Finance", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Brokerage/Investment Sales"],
    summary: "Benjamin is interested in acquisitions. They see the program as a strong place to get started in their area of interest, offering both the chance to learn and access to peers and alumni with similar interests upon completion.",
    experience: "",
  },
  {
    id: "olivia-brown", slug: "olivia-brown", name: "Olivia Brown",
    major: "Architecture", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Construction", "Property Management", "Brokerage/Investment Sales"],
    summary: "Olivia intends to enter the development field with a focus on high-density residential and mixed-use construction. As an architecture major, they are looking to build the business-related skills and knowledge they do not yet have.",
    experience: "",
  },
  {
    id: "raef-abi-chaker", slug: "raef-abi-chaker", name: "Raef Abi chaker",
    major: "Chemical engineering", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Construction", "Property Management", "Foreign Investment", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    summary: "Raef is open to and interested in all areas of real estate, with a particular focus on learning how to invest and expand within the field. They hope the program will help them learn and grow in these interests.",
    experience: "Finance and Strategy Intern at MoneyGram.",
  },
  {
    id: "sahasra-chava", slug: "sahasra-chava", name: "Sahasra Chava",
    major: "Business Adminstration, concentration in finance, minor in FinTech and/or CS", year: "Freshman", grad: "May 2029", gradYear: 2029,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Sahasra is looking to explore different areas of real estate, from making deals to financing investments, to discover where their interests lie. They hope to gain insight beyond the classroom, apply new skills in the real world, and explore a new career path through learning from industry professionals and networking.",
    experience: "Administrative Intern at a wealth management firm managing investments and real estate, where they handled bills and paperwork, communicated with multiple tenants, and coordinated with the HOA to resolve issues.",
  },
  {
    id: "rita-chen", slug: "rita-chen", name: "Rita Chen",
    major: "Business Administration, Accounting, Minor in Fintech", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Rita is most interested in development, acquisitions, and capital markets, drawn to how they combine financial analysis with strategic decision-making, and also in lending and private credit given the role of capital structure in shaping project outcomes. They are further interested in REITs and foreign investment for their exposure to large-scale, diversified portfolios and global markets. They see the Analyst Program as a structured way to build a technical and professional foundation, with its sessions on capital markets and financial modeling aligning directly with their interests, and industry events and peer collaboration deepening their understanding of the CRE industry.",
    experience: "Incoming Summer Banking Intern at Georgia Banking Company, whose business lines include commercial real estate.",
  },
  {
    id: "lily-cheng", slug: "lily-cheng", name: "Lily Cheng",
    major: "Mechanical Engineering", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Real Estate Investment Trusts (REITs)", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development", "Lending & Private Credit", "Foreign Investment", "Property Management"],
    summary: "Lily is looking to learn more about real estate and hopes the program will introduce them to new topics in the field.",
    experience: "",
  },
  {
    id: "akhila-chilumula", slug: "akhila-chilumula", name: "Akhila Chilumula",
    major: "MS. Building Construction and Facilities management", year: "Full-Time Graduate Student", grad: "fall 2025", gradYear: 2025,
    disciplines: ["Development", "Acquisitions", "Capital Markets"],
    summary: "Exploring career paths across commercial real estate.",
    experience: "",
  },
  {
    id: "roshni-chimmili", slug: "roshni-chimmili", name: "Roshni Chimmili",
    major: "Civil engineering with focus in construction and sustainable infrastructure", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Brokerage/Investment Sales", "Construction", "Property Management", "Foreign Investment", "Real Estate Investment Trusts (REITs)"],
    summary: "Roshni is especially interested in development and construction, drawn as a civil engineering student to how projects move from idea to something built and used, and to the mix of technical problem-solving with the business side of feasibility, costs, and timelines. They are also interested in brokerage/investment sales, REITs, property management, and foreign investment in order to see the full lifecycle of real estate in a global context. They see the Analyst Program as a way to bridge the gap between classroom learning and how real estate is actually financed, analyzed, and evaluated.",
    experience: "Project Engineering Intern at a management consulting firm, supporting project planning, data analysis, and coordination across stakeholders; incoming Construction and Deployment Support Intern at Lumen Technologies, working with real-world infrastructure projects, field operations, and coordination across design, construction, and deployment teams.",
  },
  {
    id: "arul-chutani", slug: "arul-chutani", name: "Arul Chutani",
    major: "Business Administration, Finance, Minor in Fintech or Psychology (have not declared yet)", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Acquisitions", "Real Estate Investment Trusts (REITs)"],
    summary: "Arul is interested in acquisitions and how firms evaluate which properties are worth buying and their long-term potential, and wants to explore capital markets to understand how deals are financed and capital is raised. They are also drawn to brokerage and investment sales, lending and private credit, and REITs, and see the Analyst Program as a chance to build on their finance background, gain hands-on experience connecting classroom learning to real projects, and test whether a career in real estate is the right fit alongside their goals in private equity.",
    experience: "",
  },
  {
    id: "isaiah-coriolan", slug: "isaiah-coriolan", name: "Isaiah Coriolan",
    major: "Industrial & Systems Engineering | Supply Chain Engineering", year: "Senior", grad: "Fall 2026", gradYear: 2026,
    disciplines: ["Property Management", "Real Estate Investment Trusts (REITs)", "Capital Markets", "Brokerage/Investment Sales", "Acquisitions", "Foreign Investment", "Lending & Private Credit", "Development", "Construction", "Local Ordinance/Zoning Laws"],
    summary: "Isaiah is primarily interested in building broad knowledge of real estate, with a particular aim of learning about investment properties for personal investing and anything transferable to that domain. They see the program as a way to develop a transferable knowledge base they can apply to personal real estate investing.",
    experience: "Co-op with Delta (three rotations, including Schedule Analytics in Network Planning, building analytical tools to support flight schedule creation); full-time summer and part-time fall internship with Americold Logistics in process improvement and data analysis for a largely automated warehouse.",
  },
  {
    id: "kyle-crain", slug: "kyle-crain", name: "Kyle Crain",
    major: "Finance", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Capital Markets", "Real Estate Investment Trusts (REITs)", "Acquisitions"],
    summary: "Exploring career paths across commercial real estate.",
    experience: "Corporate Accountant at Portman Holdings; incoming Investment Banking Analyst (summer).",
  },
  {
    id: "coleson-cunningham", slug: "coleson-cunningham", name: "Coleson Cunningham",
    major: "Aerospace Engineering (Minor in Technology and Managment pending application)", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Property Management", "Foreign Investment", "Development", "Capital Markets"],
    summary: "Coleson hopes to combine business with space, helping to build the field of space tourism where housing and entertainment centers will need to be developed, and is also interested in construction and property management with a personal goal of investing in rental properties. They look forward to gaining a more complete understanding of the real estate field beyond construction and to building their connections in the industry.",
    experience: "Worked in construction on several projects before college, including managing the budget on one project.",
  },
  {
    id: "daniel", slug: "daniel", name: "Daniel",
    major: "Construction Science and Management", year: "Sophomore", grad: "2028", gradYear: 2028,
    disciplines: ["Capital Markets", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Daniel is eager to learn more about REITs in depth, having gained some initial exposure to them over the summer. They hope to understand how real estate investing truly happens and to begin getting hands-on with deals.",
    experience: "Completed a construction internship last summer.",
  },
  {
    id: "julia-demakis", slug: "julia-demakis", name: "Julia Demakis",
    major: "Business Administration, undecided concentration (thinking about maybe strategy)", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Construction"],
    summary: "Julia is especially interested in real estate development, acquisitions, and construction, drawn to how they combine strategy, creativity, and long-term vision to create value. They are drawn to development for shaping how spaces are designed and used, to acquisitions for evaluating opportunities and market value to make informed investment decisions, and to construction for turning ideas into physical reality. Coming in with essentially no prior real estate knowledge, they see the program as a critical step to build a strong foundation and understand the financial and analytical side of the field alongside its creative aspects.",
    experience: "",
  },
  {
    id: "angie-doan", slug: "angie-doan", name: "Angie Doan",
    major: "Business Administration-Finance", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)"],
    summary: "Angie has a broad interest in acquisitions, capital markets, brokerage, lending and private credit, and REITs, having dabbled in all of these disciplines and looking to learn more about each. They see the Analyst Program as a way to learn more about real estate and specifically its financial side, whether that helps them identify a career path or supports their upcoming credit internship for real estate developments.",
    experience: "Incoming Credit Intern at Ameris Bank.",
  },
  {
    id: "peter-duarte", slug: "peter-duarte", name: "Peter Duarte",
    major: "Business Administration, Finance", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Peter is interested in learning more about the financial modeling behind real estate deals. They hope the program will help them continue building context on how real estate becomes profitable and how major projects work from start to finish.",
    experience: "Interned at a hard money lending real estate business specializing in loans to single-family home flippers; interned in the purchasing department at Gilbane Building Company this past summer.",
  },
  {
    id: "derek-duong", slug: "derek-duong", name: "Derek Duong",
    major: "business administration - accounting concentration", year: "Freshman", grad: "may 2030", gradYear: 2030,
    disciplines: ["Brokerage/Investment Sales", "Foreign Investment", "Capital Markets", "Acquisitions"],
    summary: "As an accounting major, Derek is particularly interested in gaining a general understanding of the processes involved in real estate. They see the program as a community to learn from.",
    experience: "",
  },
  {
    id: "peter-durham", slug: "peter-durham", name: "Peter Durham",
    major: "Business Administration", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Peter is interested in property management, prompted by their parents' recent property purchase, as well as acquisitions and other finance- and investment-related areas of real estate. Eager to learn more about investments and real estate, they see the Analyst Program as a way to study real-world examples of strong real estate investments and how to properly manage real estate.",
    experience: "Currently serves as a Campus Manager for UTEES, a custom apparel company.",
  },
  {
    id: "william-edgens", slug: "william-edgens", name: "William Edgens",
    major: "Business Administration - Operations and Supply Chain", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Property Management", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit", "Capital Markets", "Acquisitions", "Brokerage/Investment Sales"],
    summary: "William has a long-standing interest in development, shaped by exposure to developers through their parents' work as architects. They hope the program will build a stronger understanding of the industry at large and make it easier to get involved in the field.",
    experience: "Interned at Choate Construction, a large general contractor, assisting across the RFI, submittal, site logistics, and project management departments and contributing to decisions on a large residential project.",
  },
  {
    id: "berk-eroglu", slug: "berk-eroglu", name: "Berk Eroglu",
    major: "Mechanical Engineering", year: "Full-Time Graduate Student", grad: "Summer 2026", gradYear: 2026,
    disciplines: ["Development", "Brokerage/Investment Sales", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Berk is exploring real estate out of general interest and aims to make more informed real estate decisions in the future.",
    experience: "",
  },
  {
    id: "moiz-fakhri", slug: "moiz-fakhri", name: "Moiz Fakhri",
    major: "Industrial Engineering, Data Science, Minor in Computer Science", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions", "Brokerage/Investment Sales"],
    summary: "Moiz is keen to deepen their knowledge of real estate and finance, particularly through Excel modeling and other analytical methods, in part to prepare for an upcoming Real Estate Data Science internship. They expect the program to strengthen their Excel skills and help them think more like a domain expert in order to make better data science decisions.",
    experience: "Completed a Machine Learning Engineering internship last summer, gaining experience in how data is structured and how to extract insights from it, and has an upcoming summer internship in real estate.",
  },
  {
    id: "aly-farghali", slug: "aly-farghali", name: "Aly Farghali",
    major: "Industrial Engineering, minor in Economics", year: "Freshman", grad: "Fall 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Property Management", "Construction"],
    summary: "Aly is drawn to acquisitions and capital markets to understand how investment decisions are evaluated, financed, and executed, and how risk and return are structured across assets, as well as to brokerage and investment sales for exposure to valuation, deal sourcing, and client-facing negotiations. They are also interested in lending and private credit for their role in shaping deal feasibility and capital structure, and see the GTRE Analyst Program as a chance to gain hands-on experience in real estate finance, market analysis, and underwriting while preparing for future roles in acquisitions, capital markets, and investment sales.",
    experience: "Interned at the Kuwait Indo Trading Company (KITCO) in Kuwait City, assisting the production manager with inventory tracking and production line inspections and holding daily meetings with the HR manager. Currently works as a First Year Wellness Experience Student Assistant at Georgia Tech, supporting first-year students through wellness programming and helping organize workshops on mental health, balance, and community-building, and has secured a summer internship as a Sales Representative with Aptive Environmental in Pittsburgh.",
  },
  {
    id: "aurora-flegel", slug: "aurora-flegel", name: "Aurora Flegel",
    major: "Civil Engineering (concentration in construction and infrastructural systems engineering)", year: "Junior", grad: "May 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Development", "Construction", "Property Management", "Real Estate Investment Trusts (REITs)"],
    summary: "Aurora is primarily interested in development for its overlap with their career goals as an engineer at a construction general contractor, along with acquisitions, construction, REITs, and property management. As a civil engineering student concentrating in construction engineering, they see the Analyst Program as a way to complement their technical coursework with the business side of real estate, becoming comfortable with real estate trends, jargon, and processes and understanding how deals get made and contracts get signed.",
    experience: "Interned at Clark Construction in Nashville on the Albion Music Row Phase I project, a 29-story luxury high-rise apartment contracted at $135M, where they used Excel to organize and edit 800+ contract documents, generated a 40-item punchlist across three levels for the concrete superintendent, and communicated with tradesmen in English and Spanish.",
  },
  {
    id: "diego-fonseca", slug: "diego-fonseca", name: "Diego Fonseca",
    major: "Architecture, Minor in Sustainable Construction and Development", year: "Junior", grad: "May 2027", gradYear: 2027,
    disciplines: ["Development", "Construction", "Foreign Investment", "Property Management"],
    summary: "Diego is interested in shaping the built environment while understanding how projects operate, perform, and grow across different markets. They see the program helping them understand the full lifecycle of real estate projects, from early planning and development through construction and long-term operations.",
    experience: "Shadowed and assisted at ESG, specifically with Royal Development Company in Abu Dhabi, gaining exposure to real estate development, design, and project operations.",
  },
  {
    id: "sam-gaeta", slug: "sam-gaeta", name: "Sam Gaeta",
    major: "Business Administration, Operations and Supply Chain Management", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Sam is interested in exploring the different ways to get involved in real estate to discover which area most interests them, and sees the program helping with networking and their overall understanding of the field.",
    experience: "",
  },
  {
    id: "kendra-garcia", slug: "kendra-garcia", name: "Kendra Garcia",
    major: "Major in Management M.S", year: "Full-Time Graduate Student", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Development", "Property Management", "Construction", "Acquisitions"],
    summary: "Kendra is drawn to development for its blend of creativity, financial strategy, and community impact, construction for the tangible execution of projects, and property management for its focus on long-term value and tenant experience. They see the Analyst Program as a pivotal step in bridging their construction project management experience and real estate license pursuit with the strategic side of the industry, expanding their exposure to development, finance, and property management.",
    experience: "Worked as a project manager for a trade construction company, coordinating crews, managing budgets, and overseeing project timelines.",
  },
  {
    id: "joselin-garcia", slug: "joselin-garcia", name: "Joselin Garcia",
    major: "Business Administration, ITM", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Development", "Brokerage/Investment Sales", "Capital Markets", "Construction"],
    summary: "Joselin is drawn to areas of the industry they have long been curious about but not yet studied formally, driven by a long-standing passion for real estate as they enter the field. They see the program as a way to turn that interest into a professional skill set, learning the language of real estate and how its different sectors work together.",
    experience: "",
  },
  {
    id: "audrey-gaughan", slug: "audrey-gaughan", name: "Audrey Gaughan",
    major: "Architecture", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Construction", "Development", "Property Management"],
    summary: "Audrey is specifically interested in the business side of architecture and its connection to the real estate industry, including project development, construction, and property management. They hope the Analyst Program will help them understand this business dimension and become more well-rounded in their future career.",
    experience: "",
  },
  {
    id: "laura-gomez-rey", slug: "laura-gomez-rey", name: "Laura Gomez-Rey",
    major: "Civil Engineering", year: "Junior", grad: "Fall 2026", gradYear: 2026,
    disciplines: ["Construction", "Development", "Brokerage/Investment Sales", "Property Management"],
    summary: "Laura is interested in land development, informed by their current work as an owner's representative evaluating potential land for new Kroger stores, as well as brokerage and investment sales, construction, and property management as a civil engineering student. They aim to build a career in real estate after gaining hands-on experience in construction and consulting, and see the Analyst Program helping them understand how these areas tie into land development and construction.",
    experience: "Has worked for an engineering consulting firm, a general contractor, and as an owner's representative.",
  },
  {
    id: "will-grabowski", slug: "will-grabowski", name: "Will Grabowski",
    major: "Building construction", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Construction", "Development", "Property Management", "Real Estate Investment Trusts (REITs)"],
    summary: "Will is interested in construction, drawn by a long-standing enjoyment of building things, and sees the program supporting their career in construction.",
    experience: "Worked with a general contractor doing home renovations.",
  },
  {
    id: "brodie-grantham", slug: "brodie-grantham", name: "Brodie Grantham",
    major: "Business Administration, Finance, Minor in FinTech", year: "Senior", grad: "December 2026", gradYear: 2026,
    disciplines: ["Development", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit", "Acquisitions"],
    summary: "Brodie is drawn to areas that align with their finance background, seeking to learn how deals are structured, properties are valued, and long-term growth is created, and to gain exposure to both the financial and operational sides of real estate. They see the Analyst Program as a way to build practical skills in financial analysis and market research while expanding their network and exploring different career paths.",
    experience: "During a finance internship at Sodexo, analyzed financial trends and assisted in forecasting for client accounts, prepared financial reports and presentations highlighting key performance metrics, and collaborated with management teams to identify cost savings and efficiency improvements, strengthening skills in Excel, financial modeling, and professional communication.",
  },
  {
    id: "suvan-gumadavalli", slug: "suvan-gumadavalli", name: "Suvan Gumadavalli",
    major: "Mechanical Engineering, minor in Finance and Real Estate", year: "Freshman", grad: "Summer 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Construction", "Real Estate Investment Trusts (REITs)", "Brokerage/Investment Sales", "Mixed Use Planning"],
    summary: "Suvan is interested in real estate and understanding the market as a step toward a dream of opening a restaurant. They see the program connecting them with professionals, teaching critical knowledge about commercial real estate, and helping them develop meaningful connections.",
    experience: "Interned at the Department of Defense and the Georgia Tech Ticket Office, and served as a marketing and financial assistant to the director at an investment firm.",
  },
  {
    id: "reis-holzworth", slug: "reis-holzworth", name: "Reis Holzworth",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Capital Markets"],
    summary: "Reis is interested in how different markets for networking interact with developing opportunities, and feels the program will help them gain knowledge of the business world and how to connect.",
    experience: "",
  },
  {
    id: "david-hughes", slug: "david-hughes", name: "David Hughes",
    major: "Business Administration", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets"],
    summary: "David is interested in development for the chance to create projects that bring value to a community, acquisitions for analyzing deals and understanding what makes an investment strong, and capital markets for learning how real estate projects are financed and how investors structure deals. They believe the Analyst Program will build strong technical and analytical skills, offering hands-on experience with underwriting and financial modeling while connecting them with mentors and peers.",
    experience: "",
  },
  {
    id: "ayana-ishaque", slug: "ayana-ishaque", name: "Ayana Ishaque",
    major: "Business Administration - concentration undecided", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Real Estate Investment Trusts (REITs)"],
    summary: "Ayana is interested in development for its project management, operations, and strategy elements that align with their focus on supply chain and operations management and strategy and innovation, and in acquisitions for its mix of finance, strategy, research, negotiation, and people skills. They expect the program to strengthen their finance and strategy skills, which can be applied to any business venture.",
    experience: "",
  },
  {
    id: "wilson-iwanicki", slug: "wilson-iwanicki", name: "Wilson Iwanicki",
    major: "BSBA", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets"],
    summary: "Wilson is interested in development, motivated by family members who work in real estate development and a desire to learn more about what they do. They see the Analyst Program helping them build experience with financial models and decide whether to continue studying real estate.",
    experience: "",
  },
  {
    id: "salvador-jimenez", slug: "salvador-jimenez", name: "Salvador Jimenez",
    major: "MBA - Concentration: Finance & Business Analytics", year: "Evening Graduate Student", grad: "2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    summary: "Salvador brings extensive knowledge of construction practices and wants to gain understanding of the financial and business side of real estate development projects. They see the program offering career insights into what it is like to work in those particular job settings.",
    experience: "Prior experience includes architecture design services and real estate consulting.",
  },
  {
    id: "mkola-kapanga", slug: "mkola-kapanga", name: "Mkola Kapanga",
    major: "Master's in Structural Engineering", year: "Full-Time Graduate Student", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Construction", "Foreign Investment", "Property Management", "Acquisitions"],
    summary: "Mkola earned a real estate minor as an undergraduate and wants to keep their skills sharp, learn about the Atlanta market, and meet with companies. They see the Analyst Program as a way to potentially pursue a part-time internship and network with others who share a passion for real estate.",
    experience: "",
  },
  {
    id: "kieran-kelleher", slug: "kieran-kelleher", name: "Kieran Kelleher",
    major: "Business Administration, Finance, Computing and People", year: "Senior", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Capital Markets", "Acquisitions", "Lending & Private Credit", "Development", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)"],
    summary: "Kieran is interested in understanding the full investment lifecycle, from acquisitions and capital markets to development and REIT strategy, in order to identify value opportunities and structure deals aligned with long-term portfolio growth. They see the program helping them gain hands-on experience, industry mentorship, and technical skills to bridge classroom concepts with real-world real estate investment and development.",
    experience: "Experience spans financial analysis, business development, software development, and data analytics.",
  },
  {
    id: "kyle-king", slug: "kyle-king", name: "Kyle King",
    major: "Biology, pre-health", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Kyle is immensely interested in the investment side of real estate while expecting their interests to evolve over the semester. They see the Analyst Program as an opportunity to immerse themselves in real estate and its potential to grow their portfolio throughout their career.",
    experience: "",
  },
  {
    id: "vasudevan-lakshmanan", slug: "vasudevan-lakshmanan", name: "Vasudevan Lakshmanan",
    major: "Industrial Engineering", year: "Freshman", grad: "May 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)"],
    summary: "Vasudevan is particularly interested in the investment side of real estate, analyzing REITs and private investment, and looks to the program for professional development and networking.",
    experience: "Served as an Economic Policy Intern for the Massachusetts State House.",
  },
  {
    id: "will-lawyer", slug: "will-lawyer", name: "Will Lawyer",
    major: "MRED", year: "Evening Graduate Student", grad: "Fall 2025", gradYear: 2025,
    disciplines: ["Capital Markets", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Acquisitions", "Construction"],
    summary: "Will is looking to enhance their experience and knowledge of real estate, and sees the program helping them network and keep up with current trends and knowledge.",
    experience: "",
  },
  {
    id: "fernando-varela-leon", slug: "fernando-varela-leon", name: "Fernando Varela Leon",
    major: "Civil Engineering", year: "Junior", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Acquisitions", "Development", "Real Estate Investment Trusts (REITs)"],
    summary: "Fernando brings hands-on construction experience as a general contractor and is looking to explore the financial side of their degree through the club. They aim to develop the skills needed to enter real estate private equity and become a competitive candidate for an analyst role without a finance degree.",
    experience: "Site Developer/Concrete Subcontractor; General Contractor Project Engineer at McCarthy Buildings.",
  },
  {
    id: "nolan-mackay", slug: "nolan-mackay", name: "Nolan Mackay",
    major: "Business administration, Finance", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment", "Brokerage/Investment Sales", "Capital Markets"],
    summary: "Nolan is drawn to the financial components of real estate, with particular interest in acquisitions, lending, and private credit, and in learning how to deploy capital effectively while managing risk. They hope the analyst program will deepen their business knowledge and provide insight into a real estate field they have long found interesting and may pursue.",
    experience: "",
  },
  {
    id: "riya-makan", slug: "riya-makan", name: "Riya Makan",
    major: "Business Administration, ITM", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions", "Capital Markets"],
    summary: "Riya is interested in brokerage and investment sales. With no prior background in analysis, they value the mentorship and guidance the analyst program's structure provides.",
    experience: "",
  },
  {
    id: "sahej-mander", slug: "sahej-mander", name: "Sahej Mander",
    major: "Civil engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Construction", "Development", "Acquisitions", "Brokerage/Investment Sales", "Property Management"],
    summary: "Sahej is interested in the full life cycle of real estate assets, from acquisition and development through construction, leasing, and operations, with a focus on the value-creation process and how investment theses differ across asset types such as operating assets and REITs. They aim to gain practical experience in financial modeling, market research, and deal analysis while building a foundation for a long-term career in real estate investment and development.",
    experience: "Interned at GasPro LLC (August 2021–July 2025), assisting with operation planning for excavators, dozers, compactors, and related equipment, and interpreting site plans, architectural drawings, and building specifications alongside project supervisors.",
  },
  {
    id: "rahul-mathew", slug: "rahul-mathew", name: "Rahul Mathew",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Property Management", "Construction", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    summary: "Rahul is interested in the acquisition and renovation of property, along with brokerage, the construction process, and property management. They see the program as a way to expand their real estate knowledge and connect with others who share similar interests.",
    experience: "Worked as a frontend engineer at Deap Learning, a startup that used AI chatbots to help students learn material for their AP classes.",
  },
  {
    id: "junyi-mo", slug: "junyi-mo", name: "JunYi Mo",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Construction", "Property Management", "Foreign Investment", "Real Estate Investment Trusts (REITs)"],
    summary: "JunYi is currently a real estate agent looking to break into investments, and wants to deepen their understanding of commercial real estate to support that career move. They see the program building analytical insight that will benefit them across many aspects of the field.",
    experience: "Currently works part-time for Virtual Properties Realty.",
  },
  {
    id: "maya-morrow", slug: "maya-morrow", name: "Maya Morrow",
    major: "Economics, BSBA - IT Management", year: "Junior", grad: "2027", gradYear: 2027,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Development", "Brokerage/Investment Sales", "Acquisitions"],
    summary: "Maya is interested in a broad range of real estate disciplines, including development, acquisitions, brokerage, REITs, and property management, drawn to creating tangible projects, evaluating deals, researching markets, and strengthening their negotiation and relationship-building skills. They see the analyst program as an opportunity to gain hands-on experience, mentorship, and networking that will refine their technical skills and help identify where they can contribute most effectively.",
    experience: "At Southern Power, modernized a system that improved data workflows for over 100 field technicians and management, researched emerging technologies including AR and Matterport to enhance workforce training, and coordinated between plant staff and corporate teams on projects valued up to $50,000.",
  },
  {
    id: "kylie-mumma", slug: "kylie-mumma", name: "Kylie Mumma",
    major: "Business Administration and Economics", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Capital Markets", "Acquisitions", "Development"],
    summary: "Kylie is interested in development projects and underwriting deals, drawn to analyzing financial investments and strategic decisions. They hope to build stronger foundational knowledge of real estate and develop skills that transfer across disciplines.",
    experience: "",
  },
  {
    id: "shayne-murphy", slug: "shayne-murphy", name: "Shayne Murphy",
    major: "Industrial Engineering, Undecided", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Development", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Shayne has always been interested in real estate and is eager to learn more about the field. They value the community that clubs provide and look forward to learning both from the program and from the diverse group of members around them.",
    experience: "",
  },
  {
    id: "ethan-muyres", slug: "ethan-muyres", name: "Ethan Muyres",
    major: "Business Administration, Finance", year: "Sophomore", grad: "2028", gradYear: 2028,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    summary: "Ethan is interested in finance roles and wants to learn more about real estate as a potential sector to pursue. They hope the program will help them confirm their interest in real estate, learn new markets, build applicable skills, and land internships.",
    experience: "",
  },
  {
    id: "natalie-neymark", slug: "natalie-neymark", name: "Natalie Neymark",
    major: "Environmental Science, Minor is FinTech and Sustainable Cities", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Property Management", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development"],
    summary: "Natalie is interested in beginning to invest in real estate early and gaining hands-on experience in buying, managing, and developing properties. They aim to come away with a strong understanding of the real estate market and community.",
    experience: "",
  },
  {
    id: "jimmy-nguyen", slug: "jimmy-nguyen", name: "Jimmy Nguyen",
    major: "Business Administration, Accounting", year: "Senior", grad: "Fall 2027", gradYear: 2027,
    disciplines: ["Capital Markets", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Acquisitions", "Construction"],
    summary: "Jimmy is looking to broaden their understanding of real estate and how it relates to their major. They hope the analyst program will further develop their knowledge and interest in the field while providing valuable connections.",
    experience: "",
  },
  {
    id: "caleb-paek", slug: "caleb-paek", name: "Caleb Paek",
    major: "Industrial Engineering - Analytics and Data Science", year: "Junior", grad: "Fall 2027", gradYear: 2027,
    disciplines: ["Brokerage/Investment Sales"],
    summary: "Caleb is drawn to brokerage, which they see as analytical and relationship-driven work centered on connecting capital, clients, and property value. As an Industrial Engineering student concentrating in Analytics and Data Science, they hope to apply those skills to real-world property data.",
    experience: "",
  },
  {
    id: "jonathan-pan", slug: "jonathan-pan", name: "Jonathan Pan",
    major: "Business Administration-IT Management, minor in computing & business through Denning T&M program", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development"],
    summary: "Jonathan is interested in development and the decisions that determine which projects yield the greatest reward. They see the program as a way to learn more about real estate and the career possibilities within the field.",
    experience: "Marketing Analytics Intern at Delta Air Lines, where they built a data model powering a Tableau dashboard they designed and deployed over a 12-week internship; incoming Spring 2026 Network Planning Co-op at Delta Air Lines.",
  },
  {
    id: "dev-patel", slug: "dev-patel", name: "Dev Patel",
    major: "Business Adminstration - Finance", year: "Freshman", grad: "May 2029", gradYear: 2029,
    disciplines: ["Capital Markets", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment", "Lending & Private Credit", "Brokerage/Investment Sales"],
    summary: "Dev is interested in exploring different ways to invest in assets and identifying undervalued opportunities in areas with strong development potential. They aim to build real estate skills and learn how to evaluate property valuation.",
    experience: "",
  },
  {
    id: "aum-patel", slug: "aum-patel", name: "Aum Patel",
    major: "Business (finance concentration)", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Lending & Private Credit", "Brokerage/Investment Sales", "Property Management", "Real Estate Investment Trusts (REITs)", "Acquisitions", "Development"],
    summary: "Aum is particularly interested in REITs and property management, drawn to how they combine financial analysis with tangible assets and how strategy, operations, and financial performance connect. They hope to build stronger analytical and valuation skills while gaining hands-on exposure to how real estate investment decisions are made.",
    experience: "",
  },
  {
    id: "rishi-patel", slug: "rishi-patel", name: "Rishi Patel",
    major: "Architecture", year: "Junior", grad: "Fall 2027", gradYear: 2027,
    disciplines: ["Development", "Construction", "Property Management"],
    summary: "Rishi is interested in understanding the relationship between developers, contractors, and architects in the effort to develop Atlanta. They see the analyst program grounding them in the fundamentals of development and its connection to the construction and design industries.",
    experience: "",
  },
  {
    id: "pratham-patel", slug: "pratham-patel", name: "Pratham Patel",
    major: "Computer Science, Mod/Sim and Media", year: "Senior", grad: "Dec 2026", gradYear: 2026,
    disciplines: ["Foreign Investment", "Real Estate Investment Trusts (REITs)", "Property Management", "Construction", "Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development"],
    summary: "Pratham is most interested in lending and private credit, drawn to how those financing a property share a vested interest in its success as an investment. They hope to gain foundational skills and a taste of the different real estate disciplines before pivoting toward the one that interests them most.",
    experience: "Has software engineering internship experience, though none in real estate or finance.",
  },
  {
    id: "arjunn-patel", slug: "arjunn-patel", name: "Arjunn Patel",
    major: "Business Administration, Undecided", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Arjunn is eager to learn as much as possible, particularly within the business realm. They see the analyst program as a way to gain knowledge not otherwise available at Georgia Tech, form connections, and pursue internships and mentorship that strengthen their resume and experience.",
    experience: "",
  },
  {
    id: "svayam-patil", slug: "svayam-patil", name: "Svayam Patil",
    major: "Math major concentration in statistics and probability", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Brokerage/Investment Sales", "Lending & Private Credit", "Property Management"],
    summary: "Svayam selected development and property management, drawing on a natural passion for planning and organization and a desire to see how those skills apply to real estate. They hope to develop advanced financial modeling skills and learn to analyze and process complex market data.",
    experience: "",
  },
  {
    id: "sean-peck", slug: "sean-peck", name: "Sean Peck",
    major: "Business Administration, Finance, Minor in Computer Science", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Foreign Investment", "Property Management"],
    summary: "Sean is interested in exploring several real estate disciplines to find the one that best suits them. They hope to develop their asset analysis skills and strengthen their Excel abilities by working on real projects.",
    experience: "",
  },
  {
    id: "plern-pibuldham", slug: "plern-pibuldham", name: "Plern Pibuldham",
    major: "Civil Engineering", year: "Junior", grad: "May 2027", gradYear: 2027,
    disciplines: ["Development", "Construction", "Property Management", "Capital Markets", "Acquisitions"],
    summary: "Plern is a civil engineering major with a strong interest in sustainable construction, looking to learn about real estate to inform where and what to build. They are eager to gain real-world experience working on actual cases and to learn things not covered in the classroom.",
    experience: "Interned at Siemens as an Engineering Intern focused on construction and sustainability, analyzing and presenting energy data, calculating material costs, and gaining on-site exposure to HVAC zoning and reading floor plans.",
  },
  {
    id: "nicholas-poage", slug: "nicholas-poage", name: "Nicholas Poage",
    major: "Business, Minor in CS", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Development"],
    summary: "Nicholas finds real estate interesting and useful to understand, and hopes to learn valuable professional and personal skills through the program.",
    experience: "Incoming intern at Home Depot.",
  },
  {
    id: "connor-prather", slug: "connor-prather", name: "Connor Prather",
    major: "Economics", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Construction", "Capital Markets"],
    summary: "Connor is especially interested in designing projects and analyzing markets to determine what is most feasible. They hope to gain valuable experience in the real estate sector and learn how a project in the field comes together.",
    experience: "Worked under a local real estate development company last summer, gaining experience filling out zoning forms and evaluating development possibilities, and met in person with government officials to discuss development plans.",
  },
  {
    id: "liam-puckhaber", slug: "liam-puckhaber", name: "Liam Puckhaber",
    major: "Business Administration", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Brokerage/Investment Sales", "Development"],
    summary: "Liam is very interested in brokerage and hopes the program will expose them to more opportunities.",
    experience: "",
  },
  {
    id: "josseline-reyes-bravo", slug: "josseline-reyes-bravo", name: "Josseline Reyes-Bravo",
    major: "Majoring in Architecture", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Construction", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Josseline is drawn to real estate as a wealth-building opportunity and aims to develop foundational knowledge of the real estate process.",
    experience: "",
  },
  {
    id: "benjamin-reznikov", slug: "benjamin-reznikov", name: "Benjamin Reznikov",
    major: "Computer Science", year: "Sophomore", grad: "May 2027", gradYear: 2027,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Brokerage/Investment Sales"],
    summary: "Benjamin is particularly interested in residential investment properties, both single- and multi-family, along with syndications as a source of semi-passive income, which draws them toward property management and REITs. They are eager to broaden their overall knowledge of the industry and hope the Analyst Program will deepen their understanding of property management and equip them with the tools to enter the market and identify strong real estate investments.",
    experience: "Worked as a Research and Development Spectral Science Intern at the National Geospatial-Intelligence Agency (Summer 2024) and currently serves as a Student Research Assistant at the Georgia Tech Research Institute (GTRI), primarily working with LIDAR data.",
  },
  {
    id: "devyn-rosenberg", slug: "devyn-rosenberg", name: "Devyn Rosenberg",
    major: "Business Administration, Finance", year: "Junior", grad: "Spring 27", gradYear: 0,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Capital Markets", "Development"],
    summary: "Devyn is interested in development, acquisitions, capital markets, and lending and private credit, motivated by a desire to understand construction loans and the project lifecycle, what makes properties attractive to lenders, how economic trends and interest rates shape deals, and the quantitative side of commercial real estate. As an upcoming real estate intern, they see the program teaching both core industry concepts and the tools and platforms used in practice.",
    experience: "Accounting Intern at Cents of Mind; interned under the Practice Manager at Phoenix Ortho Injury Spine & Extremity; currently a marketing intern at Warner Bros. during the school year; expected to intern in Multifamily Lending at Greystone next summer.",
  },
  {
    id: "jocelyn-santos-reyes", slug: "jocelyn-santos-reyes", name: "Jocelyn Santos-Reyes",
    major: "M.S with a major in Management", year: "Full-Time Graduate Student", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Development", "Construction", "Property Management", "Acquisitions"],
    summary: "Jocelyn is interested in the acquisition, development, and sales process of real estate, with focus areas spanning development, acquisitions, construction, and property management. They hope the Analyst Program will strengthen their technical and verbal real estate skills to become a competitive candidate for analyst roles.",
    experience: "Interned as a real estate analyst at Waffle House, where they identified suitable sites, conducted due diligence, communicated with landowners to begin negotiations, and presented findings to the head of the Real Estate department.",
  },
  {
    id: "abhishek-sekhar", slug: "abhishek-sekhar", name: "Abhishek Sekhar",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Abhishek is drawn to the analytical, numbers-driven side of real estate, which suits their strengths. They envision a future career at a larger finance firm dealing in commodities, real estate, and other assets, and view the skills gained through the Analyst Program as broadly transferable across finance.",
    experience: "Interned during junior year of high school at an AI startup, developing a program to tutor students for the SAT based on their individual learning styles.",
  },
  {
    id: "steve-self", slug: "steve-self", name: "Steve self",
    major: "Business, accounting", year: "Part-Time Graduate Student", grad: "6/28", gradYear: 0,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    summary: "Steve is interested in real estate transactions and seeks exposure to core industry concepts.",
    experience: "",
  },
  {
    id: "saajan-shah", slug: "saajan-shah", name: "Saajan Shah",
    major: "IE, Econ and Finance, Minor in Fintech", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Brokerage/Investment Sales", "Foreign Investment", "Construction", "Development"],
    summary: "Saajan developed an early passion for real estate growing up around the hotel industry and later through exposure to the investment side, including low-income housing, short-term rentals, and large, complex deals, sparking interests across development, acquisitions, investment sales, lending and private credit, construction, and foreign investment. Looking ahead, they hope to explore different asset classes, creative deal structures, and emerging markets both domestically and internationally, combining traditional strategies with innovative approaches to build a modern, diversified real estate platform. They see the Analyst Program's structured curriculum, hands-on case study, cross-discipline exposure, mentorship, and alumni network as the foundation to bridge their background with institutional real estate investing and shape a differentiated path of their own.",
    experience: "Product Engineering Intern at IHG (Summer 2025).",
  },
  {
    id: "abhishek-shahane", slug: "abhishek-shahane", name: "Abhishek Shahane",
    major: "Industrial Engineering", year: "Freshman", grad: "Dec 2028", gradYear: 2028,
    disciplines: ["Not sure"],
    summary: "Abhishek is still exploring which areas of real estate interest them most and joined to use the Analyst Program as a guide into finance, including its technical aspects.",
    experience: "Completed a consulting internship with the City of Marietta, where they worked with a team to develop a solution for fast and efficient business permits.",
  },
  {
    id: "asa-benjamin-winter-shitey", slug: "asa-benjamin-winter-shitey", name: "Asa Benjamin Winter Shitey",
    major: "Computer Engineering", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Acquisitions", "Property Management", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit"],
    summary: "Asa is interested in developing and renting out properties in their hometown and sees the Analyst Program as an introduction to real estate and a jumping-off point.",
    experience: "",
  },
  {
    id: "leonid-shteynblik", slug: "leonid-shteynblik", name: "Leonid Shteynblik",
    major: "CIVIL ENGINEERING", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Capital Markets", "Brokerage/Investment Sales", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions"],
    summary: "Leonid enjoys construction, development, and financial modeling and hopes to gain the skills needed to eventually run their own firm. They see the program as a way to expand their skillset, learn the basics of the industry, and connect with future mentors and industry professionals.",
    experience: "Worked at Fuentes Construction, a heavy civil engineering firm focused on foundations, sheet piles, and maritime construction.",
  },
  {
    id: "monish-soniminde", slug: "monish-soniminde", name: "Monish Soniminde",
    major: "Economics, Minor in AIML, Minor in T&M", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Development", "Real Estate Investment Trusts (REITs)", "Property Management"],
    summary: "Monish is interested in an acquisitions-based role as well as development and management, recognizing that acquisitions require both. They see the program providing greater access to information, a stronger grasp of real estate technicals, and industry insights.",
    experience: "Wealth Management Intern at UBS.",
  },
  {
    id: "kathleen-spaniol", slug: "kathleen-spaniol", name: "Kathleen Spaniol",
    major: "Business Administration, no concentration as of now", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Capital Markets", "Acquisitions", "Development", "Lending & Private Credit", "Foreign Investment", "Property Management"],
    summary: "Kathleen is new to real estate and eager to learn about the field through the club, seeing the program as a source of hands-on experience that will help narrow down their career goals.",
    experience: "",
  },
  {
    id: "adam-stadelmeier", slug: "adam-stadelmeier", name: "Adam Stadelmeier",
    major: "Business Administration, Finance", year: "Sophomore", grad: "Fall 2027 or Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment", "Brokerage/Investment Sales"],
    summary: "Adam has a strong passion for entrepreneurship and wants to gain the skills needed to start their own real estate investment firm. They see the Analyst Program offering a deeper dive into the specifics of real estate, hands-on case studies, and the chance to meet like-minded peers.",
    experience: "Interned at The Whiting-Turner Contracting Company (Summer 2025); Co-Founder of CraftPost LLC.",
  },
  {
    id: "marcin-stryjecki", slug: "marcin-stryjecki", name: "Marcin Stryjecki",
    major: "MBA", year: "Full-Time Graduate Student", grad: "May 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    summary: "Marcin is interested in the finance side of real estate and seeks additional exposure to the industry.",
    experience: "",
  },
  {
    id: "ashrita-sunkara", slug: "ashrita-sunkara", name: "Ashrita Sunkara",
    major: "Indsutrial Engineering, Economic and Financial Systems", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Acquisitions", "Development", "Lending & Private Credit", "Property Management"],
    summary: "Ashrita wants to enter the finance industry and is eager to learn about the financial aspect of real estate along with financial markets and investments. They see the Analyst Program building their finance knowledge through a real estate lens while strengthening technical skills such as public speaking, networking, and communication.",
    experience: "As a first-year student, has completed a Human Resources Internship with Forsyth County Schools, which built skills in organizing a team, improving worker efficiency, and customer service, and a Social Media and Marketing Internship with Heat Dance Academy, which developed teamwork and graphic design skills.",
  },
  {
    id: "satvik-tadiparthi", slug: "satvik-tadiparthi", name: "Satvik Tadiparthi",
    major: "Architecture", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Construction", "Property Management"],
    summary: "Satvik is very interested in residential development and believes these disciplines will strengthen how they understand opportunities. As an architecture student regularly exposed to the design side, they see the Analyst Program helping them branch out and become a better leader in real estate.",
    experience: "Architectural Design Intern at GPD Group; Construction Intern at BLK Constructions.",
  },
  {
    id: "manuel-terrero", slug: "manuel-terrero", name: "Manuel Terrero",
    major: "MBA - Concentration: Undecided", year: "Evening Graduate Student", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Brokerage/Investment Sales", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Manuel is especially interested in how real estate strategy supports media companies and themed entertainment brands, where creative storytelling and large-scale development intersect. They see the program helping build their network and gain the skills needed to be competitive in the job market.",
    experience: "",
  },
  {
    id: "david-thompson", slug: "david-thompson", name: "David Thompson",
    major: "Business Administration, Finance Concentration", year: "Freshman", grad: "May 2030", gradYear: 2030,
    disciplines: ["Development", "Capital Markets", "Acquisitions", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    summary: "David is interested in finance, private equity, and asset management, and sees the program as a source of career opportunities.",
    experience: "",
  },
  {
    id: "nk-thompson", slug: "nk-thompson", name: "NK Thompson",
    major: "Civil Engineering with a construction concentration", year: "Freshman", grad: "3031", gradYear: 0,
    disciplines: ["Development", "Construction", "Property Management", "Real Estate Investment Trusts (REITs)"],
    summary: "NK wants to go into construction management, ensuring buildings are constructed properly and overseeing the site, and also has an interest in selling homes they have engineered or overseen. They see the program teaching them more about the construction market and how to communicate and network within it to grow their career.",
    experience: "",
  },
  {
    id: "alex-udoudoh", slug: "alex-udoudoh", name: "Alex Udoudoh",
    major: "Civil Engineering", year: "Freshman", grad: "May 2030", gradYear: 2030,
    disciplines: ["Property Management", "Construction", "Development"],
    summary: "Alex is interested in the civil engineering side of real estate and in creating an additional stream of revenue. They see the program helping them learn and build connections to position themselves ahead in the field.",
    experience: "Interned with American Medical Response for a summer.",
  },
  {
    id: "patrick-vettickatt", slug: "patrick-vettickatt", name: "Patrick Vettickatt",
    major: "Industrial Engineering", year: "Sophomore", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    summary: "Patrick is interested in applying the math and science of industrial engineering, especially modeling, statistics, and programming, to financial decision-making. They see the program helping them learn more about real estate and its opportunities, find where they fit, break into the field, and develop soft skills such as networking.",
    experience: "Process Improvement Intern at GE Vernova; upcoming Process Quality Engineer Intern at Walmart (Summer 2026).",
  },
  {
    id: "avery-watts", slug: "avery-watts", name: "Avery Watts",
    major: "Industrial Engineering", year: "Sophomore", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    summary: "Avery is an industrial engineer concentrating in Financial and Economic Systems, with a particular interest in optimizing prices, places, and systems, and has been building a baseline understanding across many real estate topics. They are especially interested in the investment side of real estate, particularly valuing lots and sites for future building, and are motivated by seeing a plan come together and making a tangible impact on places and communities.",
    experience: "",
  },
  {
    id: "mason-williams", slug: "mason-williams", name: "Mason Williams",
    major: "Business Administration - Finance", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Property Management", "Acquisitions"],
    summary: "Mason is interested in learning how money flows through acquisition and development, and sees the program broadening their networking, Excel, and corporate knowledge and skills.",
    experience: "",
  },
  {
    id: "allison-wong", slug: "allison-wong", name: "Allison Wong",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales"],
    summary: "Allison is interested in acquisitions, where they can analyze opportunities and weigh the pros and cons; capital markets, where they enjoy seeing how economics fits together to create a financial system; and brokerage and investment sales, where they can develop their sales skills. As an industrial engineering student, they want to build specialties, including real estate.",
    experience: "",
  },
  {
    id: "jisang-yoon", slug: "jisang-yoon", name: "Jisang Yoon",
    major: "Aerospace Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development", "Lending & Private Credit", "Construction"],
    summary: "Jisang is interested in property management and sees the program as a way to learn more about real estate through hands-on experience.",
    experience: "",
  },
];

export const MEMBER_DISCIPLINES = Array.from(new Set(MEMBERS.flatMap((m) => m.disciplines))).sort();
export const MEMBER_GRAD_YEARS = Array.from(new Set(MEMBERS.map((m) => m.gradYear).filter(Boolean))).sort();

export function memberInitials(name: string): string {
  return name.split(' ').filter(Boolean).map((p) => p[0]).slice(0, 2).join('').toUpperCase();
}
