// Analyst Rolodex roster — this year's Mentorship Program members, extracted
// from their new-member form responses. Contact details (phone, personal and
// GT email) are intentionally NOT stored here. Photos are added later; until
// then each card shows an initials avatar. This file is generated from the
// club's response sheet; edit the roster in the sheet and re-generate.

export type RolodexMember = {
  id: string;
  slug: string;
  name: string;
  major: string;
  year: string;
  grad: string;
  gradYear: number;
  disciplines: string[];
  interests: string;
  experience: string;
};

export const MEMBERS: RolodexMember[] = [
  {
    id: "alexander-abdallah", slug: "alexander-abdallah", name: "Alexander Abdallah",
    major: "Business finance", year: "Junior", grad: "December 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Capital Markets", "Real Estate Investment Trusts (REITs)"],
    interests: "I am highly interested in real estate as a career. I’m still exploring my options and looking to learn more.",
    experience: "None that are related to this field.",
  },
  {
    id: "jared-abrahamian", slug: "jared-abrahamian", name: "Jared Abrahamian",
    major: "Masters of Architecture", year: "Full-Time Graduate Student", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Development", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "I'm mainly interested in getting a deeper understanding in Real Estate Development and how I can connect my experience in Architecture to it.",
    experience: "Design Intern at Formations Studio, Business Consultant for Caterpillar, Design & Fabrication Intern at GaTech",
  },
  {
    id: "emmie-adams", slug: "emmie-adams", name: "Emmie Adams",
    major: "Construction Science and Management", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Brokerage/Investment Sales", "Acquisitions", "Capital Markets", "Development"],
    interests: "My particular interests noted above reflect my desire to explore commercial real estate as a potential career path while building a foundation in development, construction, and finance. As a Construction Science and Management student, I am drawn to development and construction because they align with my academic background and understanding of how projects are planned and built. I am also interested in acquisitions, capital markets, and brokerage/investment sales because I want to gain a deeper understanding of the financial/transactional side of commercial real estate. Together, these disciplines would allow me to develop a well-rounded perspective as I learn about the industry.",
    experience: "",
  },
  {
    id: "andrew-alvarez", slug: "andrew-alvarez", name: "Andrew Alvarez",
    major: "Industrial Engineering", year: "Freshman", grad: "2029", gradYear: 2029,
    disciplines: ["Acquisitions", "Capital Markets", "Property Management"],
    interests: "I am interested these topics specifically acquisition and property management because I am interested to learn and see how decisions are made on what properties to purchase and how to manage prices of properties in comparison to surrounding properties in order to maximize profits of a location.",
    experience: "",
  },
  {
    id: "dhilan-anand", slug: "dhilan-anand", name: "Dhilan Anand",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Property Management"],
    interests: "I’d love to learn more about brokerage/investments as I’m interesting in seeing how money is used with acquisitions and large-scale projects.",
    experience: "Starting as an intern with Project Destined through their Real Estate Private Equity Program.",
  },
  {
    id: "alvaro-saldarriaga-arcila", slug: "alvaro-saldarriaga-arcila", name: "Alvaro Saldarriaga Arcila",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 20209", gradYear: 0,
    disciplines: ["Development", "Construction", "Property Management", "Brokerage/Investment Sales"],
    interests: "I would like to learn more about the foundation and the development to have a strong base on the real state industry.",
    experience: "",
  },
  {
    id: "alexander-arredondo", slug: "alexander-arredondo", name: "Alexander Arredondo",
    major: "Mechanical Engineer", year: "Senior", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions"],
    interests: "I am interested in getting to know how to acquire property and have that as a passive income",
    experience: "Project Engineer, Developing technical solutions for construction sites and implementing safety standards",
  },
  {
    id: "andrew-best", slug: "andrew-best", name: "Andrew Best",
    major: "Business Administration, Finance", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    interests: "I am interested in learning about all aspects of real estate to see what appeals to me the most.",
    experience: "Incoming Finance intern at Pratt Industries",
  },
  {
    id: "benjamin-blakeley", slug: "benjamin-blakeley", name: "Benjamin Blakeley",
    major: "Business Administration Finance", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Brokerage/Investment Sales"],
    interests: "Acquisitions",
    experience: "",
  },
  {
    id: "olivia-brown", slug: "olivia-brown", name: "Olivia Brown",
    major: "Architecture", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Construction", "Property Management", "Brokerage/Investment Sales"],
    interests: "I intend on entering the development field with a focus on high density residential and mix-use construction.",
    experience: "",
  },
  {
    id: "raef-abi-chaker", slug: "raef-abi-chaker", name: "Raef Abi chaker",
    major: "Chemical engineering", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Construction", "Property Management", "Foreign Investment", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    interests: "Open and interested in everything, specifically trying to learn how to invest and expand in real estate",
    experience: "Money gram finance and strategy intern",
  },
  {
    id: "sahasra-chava", slug: "sahasra-chava", name: "Sahasra Chava",
    major: "Business Adminstration, concentration in finance, minor in FinTech and/or CS", year: "Freshman", grad: "May 2029", gradYear: 2029,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "I don’t have much direct experience in real estate yet, which is why I want to explore different areas to see my interests. I chose the topics above so that I could see different aspects of real estate from making deals to financing investments.",
    experience: "I have worked as an administrative intern at a wealth management firm that manages investments and real estate. I managed the bills and paperwork, communicated with multiple tenants, and coordinated with the HOA to resolve issues",
  },
  {
    id: "rita-chen", slug: "rita-chen", name: "Rita Chen",
    major: "Business Administration, Accounting, Minor in Fintech", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I am most interested in development, acquisitions, and capital markets because they combine financial analysis with strategic decision making. I enjoy evaluating opportunities, understanding how value is created, and using data to assess risk and return. I am also interested in lending and private credit because of the role capital structure plays in shaping outcomes for real estate projects. REITs and foreign investment appeal to me because they offer exposure to large-scale, diversified portfolios and global markets.",
    experience: "I have not had previous internship experience, but I am an incoming summer banking intern at Georgia Banking Company, and one of their business lines is commercial real estate.",
  },
  {
    id: "lily-cheng", slug: "lily-cheng", name: "Lily Cheng",
    major: "Mechanical Engineering", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Real Estate Investment Trusts (REITs)", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development", "Lending & Private Credit", "Foreign Investment", "Property Management"],
    interests: "Just wanting to learn more.",
    experience: "",
  },
  {
    id: "akhila-chilumula", slug: "akhila-chilumula", name: "Akhila Chilumula",
    major: "MS. Building Construction and Facilities management", year: "Full-Time Graduate Student", grad: "fall 2025", gradYear: 2025,
    disciplines: ["Development", "Acquisitions", "Capital Markets"],
    interests: "N/A",
    experience: "It was good but not the best",
  },
  {
    id: "roshni-chimmili", slug: "roshni-chimmili", name: "Roshni Chimmili",
    major: "Civil engineering with focus in construction and sustainable infrastructure", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Brokerage/Investment Sales", "Construction", "Property Management", "Foreign Investment", "Real Estate Investment Trusts (REITs)"],
    interests: "I’m especially interested in development and construction because I’m studying civil engineering and want to understand how projects move from an idea to something that actually gets built and used by people. I like the mix of technical problem-solving with the business side of real estate, like understanding feasibility, costs, timelines, and how decisions affect both the project and the community. I’m also interested in brokerage/investment sales, REITs, and property management because I want to see the full lifecycle of real estate — from financing and acquisition to operating and managing properties over time. Learning about foreign investment is important to me too since real estate is global and investment decisions are influenced by international markets and capital.",
    experience: "I previously interned at a management consulting firm as a Project Engineering Intern, where I supported project planning, data analysis, and coordination across different stakeholders.I also have an upcoming internship with Lumen Technologies as a Construction and Deployment Support Intern, where I’ll be exposed to real-world infrastructure projects, field operations, and coordination between design, construction, and deployment teams.",
  },
  {
    id: "arul-chutani", slug: "arul-chutani", name: "Arul Chutani",
    major: "Business Administration, Finance, Minor in Fintech or Psychology (have not declared yet)", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Acquisitions", "Real Estate Investment Trusts (REITs)"],
    interests: "I’m really interested in learning more about acquisitions because I want to understand how firms figure out which properties are worth buying and how they evaluate long-term potential. From there, I’d also like to explore capital markets to see how deals are financed and how raising capital actually comes together in practice. On top of that, brokerage and investment sales stand out to me because I want to learn how market knowledge and relationships play a role in bringing buyers and sellers together. At the same time, lending and private credit catch my attention since I’d like to better understand how credit risk is assessed and how financing terms are set. Lastly, I’d like to dive into REITs because I think it’s interesting how they connect real estate with the public markets, and I want to get a clearer picture of how they operate and grow.",
    experience: "",
  },
  {
    id: "isaiah-coriolan", slug: "isaiah-coriolan", name: "Isaiah Coriolan",
    major: "Industrial & Systems Engineering | Supply Chain Engineering", year: "Senior", grad: "Fall 2026", gradYear: 2026,
    disciplines: ["Property Management", "Real Estate Investment Trusts (REITs)", "Capital Markets", "Brokerage/Investment Sales", "Acquisitions", "Foreign Investment", "Lending & Private Credit", "Development", "Construction", "Local Ordinance/Zoning Laws"],
    interests: "Primarily just interested in acquiring more knowledge about real estate as a whole. I would like to look into investment properties as a personal investment, so I'd like to learn more about anything that would be transferrable to this domain.",
    experience: "Coop w/Delta (3 rotations come this summer): Schedule Analytics in Network Planning- Building Analytical tools supporting flight schedule creation. Full-time Summer & Part-time fall internship w/Americold Logistics: Process Improvement, Data Analysis for a mostly automated warehouse..",
  },
  {
    id: "kyle-crain", slug: "kyle-crain", name: "Kyle Crain",
    major: "Finance", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Capital Markets", "Real Estate Investment Trusts (REITs)", "Acquisitions"],
    interests: "N/A",
    experience: "Current copeoare accountant at Portman holdings and incoming IB analyst (summer)",
  },
  {
    id: "coleson-cunningham", slug: "coleson-cunningham", name: "Coleson Cunningham",
    major: "Aerospace Engineering (Minor in Technology and Managment pending application)", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Property Management", "Foreign Investment", "Development", "Capital Markets"],
    interests: "In my career, I hope to combine business with space, helping to build the field of space tourism. Housing and entertainment centers will need to be developed in space. More personally, I hope to invest in rental properties, leading to my interests in construction and property management.",
    experience: "Before college I worked in construction for a few projects. I managed the budget on one of the projects. Otherwise, N/A.",
  },
  {
    id: "daniel", slug: "daniel", name: "Daniel",
    major: "Construction Science and Management", year: "Sophomore", grad: "2028", gradYear: 2028,
    disciplines: ["Capital Markets", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I really want to learn more about REITs and I learned a bit about them over the summer and want to know more about them in debth.",
    experience: "I have done a construction internship from last summer.",
  },
  {
    id: "julia-demakis", slug: "julia-demakis", name: "Julia Demakis",
    major: "Business Administration, undecided concentration (thinking about maybe strategy)", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Construction"],
    interests: "I am especially interested in real estate development, aquisitions, and construstion because it allows me to be involved in the process of creating value. Development is appealing to me because of how it combines strategy, creativity, and the long-term vision of shaping spaces and deciding how they are designed and used. I am also interested in acquisitions to help me develop real life skills that I can put into use of evaluating opportunities and understanding market value in order to make informed investment decisions. Finally, construction is appealing to me because its how ideas turn into physical reality, which is rewarding. All these areas are of interest to me because of both the analytical and creative sides of real estate.",
    experience: "",
  },
  {
    id: "angie-doan", slug: "angie-doan", name: "Angie Doan",
    major: "Business Administration-Finance", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)"],
    interests: "I have a broad interest in acquisitions, capital markets, brokerage, lending & private credit, and REITs. I have dabbled in all of these disciplines and look to learn more about each of them.",
    experience: "N/A-- upcoming internship at Ameris Bank as a Credit Intern",
  },
  {
    id: "peter-duarte", slug: "peter-duarte", name: "Peter Duarte",
    major: "Business Administration, Finance", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "Learn more about the financial modeling behind real estate deals",
    experience: "Interned at a hard money lending real estate business that specializes in lending money to people who flip single family homes. I also interned at Gilbane Building Company this past summer in the purchasing department",
  },
  {
    id: "derek-duong", slug: "derek-duong", name: "Derek Duong",
    major: "business administration - accounting concentration", year: "Freshman", grad: "may 2030", gradYear: 2030,
    disciplines: ["Brokerage/Investment Sales", "Foreign Investment", "Capital Markets", "Acquisitions"],
    interests: "as an accounting major, i am particularly interested in generally just understanding the processes of real estate",
    experience: "",
  },
  {
    id: "peter-durham", slug: "peter-durham", name: "Peter Durham",
    major: "Business Administration", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "Property Management because my parents just bought property and I want to help out with management. Acquisitions because my friend's dad does acquisitions and it seems interesting to me. The other interests because they are all related to finance/investment and I am interested in learning more about this.",
    experience: "I am currently a Campus Manager for UTEES, a custom apparel company but I have never had an internship.",
  },
  {
    id: "william-edgens", slug: "william-edgens", name: "William Edgens",
    major: "Business Administration - Operations and Supply Chain", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Property Management", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit", "Capital Markets", "Acquisitions", "Brokerage/Investment Sales"],
    interests: "I have always been interested in development. Both my parents are architects and I have the opportunity to meet a lot of their clients who are developers and I have always been very interested in what they do.",
    experience: "I worked for a large General Contractor (Choate Construction) where I helped in the RFI, Submittal, site logistics, and project management departments. My internship threw me into the deep end quickly by making me make decisions that could ultimately harm the large residential project I was on.",
  },
  {
    id: "berk-eroglu", slug: "berk-eroglu", name: "Berk Eroglu",
    major: "Mechanical Engineering", year: "Full-Time Graduate Student", grad: "Summer 2026", gradYear: 2026,
    disciplines: ["Development", "Brokerage/Investment Sales", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "Seemed interesting",
    experience: "",
  },
  {
    id: "moiz-fakhri", slug: "moiz-fakhri", name: "Moiz Fakhri",
    major: "Industrial Engineering, Data Science, Minor in Computer Science", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions", "Brokerage/Investment Sales"],
    interests: "I am really interested in learning more about real estate and finance especially through modeling in Excel and other various methods. I recently got an internship for Real Estate Data Science internship and I want to prepare for it by learning more about Real Estate.",
    experience: "I had a Machine Learning Engineering internship last summer and learned a lot about how data is structured and how to extract insights from it. I also have an upcoming summer internship in Real Estate.",
  },
  {
    id: "aly-farghali", slug: "aly-farghali", name: "Aly Farghali",
    major: "Industrial Engineering, minor in Economics", year: "Freshman", grad: "Fall 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Property Management", "Construction"],
    interests: "I’m interested in acquisitions and capital markets to better understand how investment decisions are evaluated, financed, and executed, as well as how risk and return are structured across different assets. I am also drawn to brokerage and investment sales for the exposure they provide to valuation, deal sourcing, and client-facing negotiations. Lending and private credit interest me because of their role in shaping deal feasibility and capital structure.",
    experience: "I have completed an internship at the Kuwait Indo Trading Company (KITCO) in Kuwait City, Kuwait where I assisted the production manager with inventory tracking and production line inspections and held daily meetings with the HR manager. I currently work as a First Year Wellness Experience Student Assistant at Georgia Tech, supporting first-year students’ transition to college through wellness programming, peer engagement, and resource guidance. I also assist with organizing workshops and activities focused on mental health, balance, and community-building. For this summer, I have secured an internship in Pittsburg with Aptive Environmental as a Sales Respresentative selling pest control and have been extensively training the last month.",
  },
  {
    id: "aurora-flegel", slug: "aurora-flegel", name: "Aurora Flegel",
    major: "Civil Engineering (concentration in construction and infrastructural systems engineering)", year: "Junior", grad: "May 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Development", "Construction", "Property Management", "Real Estate Investment Trusts (REITs)"],
    interests: "Development: I am primarily interested in development, as this has the most overlap with my career goals as an engineer at a construction general contractor. In a meeting with an executive of one of these contracting companies, he emphasized the importance of business skills. I think better understanding development would be a logical first step. Acquisitions: At the GC I interned with this summer, there was a national acquisition (and development) team. Again, since I am seeing a direct reference to these aspects of the real estate world in my professional experiences, I want to learn more and be prepared to join these conversations. Construction: I am a civil engineering student with a concentration in construction engineering. I am very passionate about overseeing and managing construction projects through a GC. Still, I have the technical knowledge through my coursework, but I would appreciate the business side of construction I may not otherwise be exposed to in my classes. REITs: I have no idea what these are, but I am intrigued and would like to learn more. Property Management: After interacting with some property managers this summer, I want to better understand that profession, even though this work is usually out of the scope of a GC.",
    experience: "I interned at Clark Construction in Nashville, TN this summer at the Albion Music Row Phase I project, a 29-story high-rise luxury apartment contracted at $135M. I used Excel to organize and edit 800+ contract documents. I generated a 40 item punchlist for 3 levels to give to the concrete superintendent. I also communicated with tradesmen in English and Spanish throughout this experience.",
  },
  {
    id: "diego-fonseca", slug: "diego-fonseca", name: "Diego Fonseca",
    major: "Architecture, Minor in Sustainable Construction and Development", year: "Junior", grad: "May 2027", gradYear: 2027,
    disciplines: ["Development", "Construction", "Foreign Investment", "Property Management"],
    interests: "shape the built environment while understanding how projects operate, perform, and grow across different markets.",
    experience: "I shadowed and assisted at ESG, specifically with Royal Development Company in Abu Dhabi, gaining exposure to real estate development, design, and project operations.",
  },
  {
    id: "sam-gaeta", slug: "sam-gaeta", name: "Sam Gaeta",
    major: "Business Administration, Operations and Supply Chain Management", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "I am interested in exploring the different ways to get involved with Real Estate and seeing what area peaks my interest.",
    experience: "",
  },
  {
    id: "kendra-garcia", slug: "kendra-garcia", name: "Kendra Garcia",
    major: "Major in Management M.S", year: "Full-Time Graduate Student", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Development", "Property Management", "Construction", "Acquisitions"],
    interests: "I’m drawn to Development for its blend of creativity, financial strategy, and community impact, Construction for the tangible execution of projects, and Property Management for its focus on long-term value and tenant experience. Networking in these fields will help me understand the full real estate lifecycle and how these disciplines intersect, preparing me to contribute to projects that succeed both financially and for communities.",
    experience: "I worked as a project manager for a trade construction company, where I coordinated crews, managed budgets, and oversaw project timelines, gaining hands-on experience in real estate operations and construction management.",
  },
  {
    id: "joselin-garcia", slug: "joselin-garcia", name: "Joselin Garcia",
    major: "Business Administration, ITM", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Development", "Brokerage/Investment Sales", "Capital Markets", "Construction"],
    interests: "These specific areas caught my eye because they represent the parts of the industry I’ve always been curious about but haven't had the chance to study formally yet. I’ve had a long-standing passion for real estate, but as I am just entering the field, I haven't known exactly where to start.",
    experience: "",
  },
  {
    id: "audrey-gaughan", slug: "audrey-gaughan", name: "Audrey Gaughan",
    major: "Architecture", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Construction", "Development", "Property Management"],
    interests: "I am specifically interested in the business side of architecture and its connection to the real estate industry (project development, construction, property management, etc)",
    experience: "",
  },
  {
    id: "laura-gomez-rey", slug: "laura-gomez-rey", name: "Laura Gomez-Rey",
    major: "Civil Engineering", year: "Junior", grad: "Fall 2026", gradYear: 2026,
    disciplines: ["Construction", "Development", "Brokerage/Investment Sales", "Property Management"],
    interests: "I'm learning in learning about land development as I am currently working as an owners representative looking at potential land for new Kroger stores. I'm also intrested in brokerage/investment sales as that ties into finanlizing a sale after scoping potential land. Lastly, construction and property management interest me as a Civil Engineering interested in the construction world.",
    experience: "I have worked for an engineering consulting firm, a general contractor, and as an owner representative.",
  },
  {
    id: "will-grabowski", slug: "will-grabowski", name: "Will Grabowski",
    major: "Building construction", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Construction", "Development", "Property Management", "Real Estate Investment Trusts (REITs)"],
    interests: "Construction, always like building things",
    experience: "Worked with general contractor doing home renovations",
  },
  {
    id: "brodie-grantham", slug: "brodie-grantham", name: "Brodie Grantham",
    major: "Business Administration, Finance, Minor in FinTech", year: "Senior", grad: "December 2026", gradYear: 2026,
    disciplines: ["Development", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit", "Acquisitions"],
    interests: "These areas align with my finance background and give me the opportunity to learn how deals are structured, properties are valued, and long-term growth is created. I want to gain exposure to both the financial and operational sides of real estate while building a strong professional network.",
    experience: "During my finance internship at Sodexo, I analyzed financial trends and assisted in forecasting to support decision-making for client accounts. I prepared financial reports and presentations that highlighted key performance metrics, and I collaborated with management teams to identify areas for cost savings and efficiency improvements. This experience strengthened my skills in Excel, financial modeling, and professional communication while giving me exposure to corporate finance in a global company.",
  },
  {
    id: "suvan-gumadavalli", slug: "suvan-gumadavalli", name: "Suvan Gumadavalli",
    major: "Mechanical Engineering, minor in Finance and Real Estate", year: "Freshman", grad: "Summer 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Construction", "Real Estate Investment Trusts (REITs)", "Brokerage/Investment Sales", "Mixed Use Planning"],
    interests: "I have a dream of opening up a restaurant and feel like these fields and understanding the market will help me with that.",
    experience: "Interned at the DoD, Georgia Tech Ticket Office, and marketing and financial assistant to director at investment firm.",
  },
  {
    id: "reis-holzworth", slug: "reis-holzworth", name: "Reis Holzworth",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Capital Markets"],
    interests: "I’m interested in how different markets for networking interact with developing opportunities",
    experience: "",
  },
  {
    id: "david-hughes", slug: "david-hughes", name: "David Hughes",
    major: "Business Administration", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets"],
    interests: "I am interested in development because I like the idea of creating projects that bring value to a community. I am interested in acquisitions because I enjoy analyzing deals and understanding what makes an investment strong. Capital markets interests me because I want to learn how real estate projects are financed and how investors structure deals.",
    experience: "",
  },
  {
    id: "ayana-ishaque", slug: "ayana-ishaque", name: "Ayana Ishaque",
    major: "Business Administration - concentration undecided", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Real Estate Investment Trusts (REITs)"],
    interests: "Development - Involves project management, operations, and strategy which aligns with my interests in supply chain & operations management and strategy & innovation. Acquisitions - analytical + includes people skills and negotiation, I like that this is a mix of finance, strategy, and research.",
    experience: "",
  },
  {
    id: "wilson-iwanicki", slug: "wilson-iwanicki", name: "Wilson Iwanicki",
    major: "BSBA", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Acquisitions", "Capital Markets"],
    interests: "I am interested in Development primarily because I have family who work in real estate development and I want to know more about what they do.",
    experience: "",
  },
  {
    id: "salvador-jimenez", slug: "salvador-jimenez", name: "Salvador Jimenez",
    major: "MBA - Concentration: Finance & Business Analytics", year: "Evening Graduate Student", grad: "2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    interests: "I have an extensive knowledge of construction practices and would like to gain knowledge on the financial and business end of real estate development projects.",
    experience: "this would be my first attempt since joining Georgia Tech, my prior experience deals with architecture design services and real estate consulting.",
  },
  {
    id: "mkola-kapanga", slug: "mkola-kapanga", name: "Mkola Kapanga",
    major: "Master's in Structural Engineering", year: "Full-Time Graduate Student", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Construction", "Foreign Investment", "Property Management", "Acquisitions"],
    interests: "During my undergraduate years, I obtained a real estate minor and I would like to keep my skills sharp, learn about the Atlanta market, and meet with companies.",
    experience: "",
  },
  {
    id: "kieran-kelleher", slug: "kieran-kelleher", name: "Kieran Kelleher",
    major: "Business Administration, Finance, Computing and People", year: "Senior", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Capital Markets", "Acquisitions", "Lending & Private Credit", "Development", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)"],
    interests: "I’m interested in understanding the full investment lifecycle—from acquisitions and capital markets to development and REIT strategy—so I can identify value opportunities and structure deals that align with long-term portfolio growth.",
    experience: "Financial Analyst, Business Development, Software Developer, Data Analytics",
  },
  {
    id: "kyle-king", slug: "kyle-king", name: "Kyle King",
    major: "Biology, pre-health", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I am immensely interested in the investment side of real estate, but I assume my interests will evolve as the semester goes on.",
    experience: "",
  },
  {
    id: "vasudevan-lakshmanan", slug: "vasudevan-lakshmanan", name: "Vasudevan Lakshmanan",
    major: "Industrial Engineering", year: "Freshman", grad: "May 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)"],
    interests: "I'm interested particularly in investment, analyzing REIT and Private Investment.",
    experience: "Economic Policy Intern for MA State House",
  },
  {
    id: "will-lawyer", slug: "will-lawyer", name: "Will Lawyer",
    major: "MRED", year: "Evening Graduate Student", grad: "Fall 2025", gradYear: 2025,
    disciplines: ["Capital Markets", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Acquisitions", "Construction"],
    interests: "I'm looking to enhance my experience and my knowledge.",
    experience: "",
  },
  {
    id: "fernando-varela-leon", slug: "fernando-varela-leon", name: "Fernando Varela Leon",
    major: "Civil Engineering", year: "Junior", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Construction", "Acquisitions", "Development", "Real Estate Investment Trusts (REITs)"],
    interests: "I already have experience in the construction field as a General Contractor, but I want to explore my degree on the financial side and I think this club would be the perfect platform.",
    experience: "Site Developer/ Concrete Subcontractor, General Contractor Project Engineer (McCarthy Buildings)",
  },
  {
    id: "nolan-mackay", slug: "nolan-mackay", name: "Nolan Mackay",
    major: "Business administration, Finance", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment", "Brokerage/Investment Sales", "Capital Markets"],
    interests: "Interested in the financial components of real estate. While I selected many of the options above, I am most interested in acquisitions and lending and private credit. Just learning how to take a lump some of money and be able to apply it in a beneficial way that may involve risk.",
    experience: "",
  },
  {
    id: "riya-makan", slug: "riya-makan", name: "Riya Makan",
    major: "Business Administration, ITM", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions", "Capital Markets"],
    interests: "Brokerage/ Investment Sales",
    experience: "",
  },
  {
    id: "sahej-mander", slug: "sahej-mander", name: "Sahej Mander",
    major: "Civil engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Construction", "Development", "Acquisitions", "Brokerage/Investment Sales", "Property Management"],
    interests: "Specifically, I am interested in the entire life cycle of real estate assets, from acquisition and development to construction, leasing, and operation. I am interested in the value-creation process that occurs as a result of development execution, brokerage, and property management as a result of underwriting and capital structure decisions made during the acquisition phase. I am particularly interested in learning more about the differences in investment theses for various types of assets, such as operating assets and REITs, and how various teams manage risk, return, and efficiency during the hold period. I believe that networking with professionals in these various fields would allow me to learn more about the role of cross-functional collaboration in successful real estate investments.",
    experience: "I interned at GasPro LLC from August 2021- July 2025. I Observed and assisted with operation planning for excavators, dozers, compactors, and related equipment. I also Interpreted site plans, architectural drawings, and building specifications alongside project supervisors.",
  },
  {
    id: "rahul-mathew", slug: "rahul-mathew", name: "Rahul Mathew",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Property Management", "Construction", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    interests: "Interested in acquisitions and renovations of property. Also interested in working with a brokerage as well the whole construction process and how to manage a property.",
    experience: "I worked as a Frontend engineer at a startup called Deap Learning which used AI chatbots to help students learn material for their AP classes.",
  },
  {
    id: "junyi-mo", slug: "junyi-mo", name: "JunYi Mo",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Construction", "Property Management", "Foreign Investment", "Real Estate Investment Trusts (REITs)"],
    interests: "Currently, I am a real estate agent looking to break into investments in the future. I want to learn more about the commercial real estate to aid with my journey in this career.",
    experience: "Currently working part-time for Virtual Properties Realty.",
  },
  {
    id: "maya-morrow", slug: "maya-morrow", name: "Maya Morrow",
    major: "Economics, BSBA - IT Management", year: "Junior", grad: "2027", gradYear: 2027,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Development", "Brokerage/Investment Sales", "Acquisitions"],
    interests: "I’m interested in development as I like the idea of creating something tangible from the ground up and seeing a project progress from concept to completion. I’m also drawn to acquisitions and brokerage since I enjoy evaluating deals, researching markets, and understanding what drives value, and I’m interested in strengthening my negotiation and relationship-building skills in real transactions. I’m curious to learn more about REITs because I currently invest in them and want a deeper understanding of how they structure portfolios and generate returns. Property management also appeals to me, as I’m comfortable taking responsibility in operational roles and would like to better understand how properties are run effectively while maintaining value and tenant satisfaction. Overall, I’m excited to explore multiple areas of real estate to build a well-rounded understanding of the industry.",
    experience: "At Southern Power, I modernized a system that improved data workflows for over 100 field technicians and higher management. I also researched emerging technologies, including AR and Matterport, to enhance workforce training, and coordinated between plant staff and corporate teams on projects valued up to $50,000. This experience strengthened my problem-solving, project coordination, and ability to translate technical needs into practical solutions.",
  },
  {
    id: "kylie-mumma", slug: "kylie-mumma", name: "Kylie Mumma",
    major: "Business Administration and Economics", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Capital Markets", "Acquisitions", "Development"],
    interests: "These are interesting to me because I want to be part of the development projects or underwriting deals, which involve analyzing financial investments and strategic decisions because I find that type of work to be the most engaging and also will teach valuable skills that are useful across industries.",
    experience: "",
  },
  {
    id: "shayne-murphy", slug: "shayne-murphy", name: "Shayne Murphy",
    major: "Industrial Engineering, Undecided", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Development", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "I have always been interested in real estate but I really don't know much about it, I am excited to learn more and these are all topics I have heard about/",
    experience: "N/A - Studied abroad freshman year summer",
  },
  {
    id: "ethan-muyres", slug: "ethan-muyres", name: "Ethan Muyres",
    major: "Business Administration, Finance", year: "Sophomore", grad: "2028", gradYear: 2028,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    interests: "I am interested in any finance roles and want to learn more about real estate and maybe get into that sector of business. It has always peaked my interest growing up and I know it will always be around.",
    experience: "",
  },
  {
    id: "natalie-neymark", slug: "natalie-neymark", name: "Natalie Neymark",
    major: "Environmental Science, Minor is FinTech and Sustainable Cities", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Property Management", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development"],
    interests: "I’m interested in these because I want to start investing in real estate early and gain hands-on experience in buying, managing, and developing properties.",
    experience: "",
  },
  {
    id: "jimmy-nguyen", slug: "jimmy-nguyen", name: "Jimmy Nguyen",
    major: "Business Administration, Accounting", year: "Senior", grad: "Fall 2027", gradYear: 2027,
    disciplines: ["Capital Markets", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Acquisitions", "Construction"],
    interests: "These interests are of most particular interest to me, as gaining additional information and exposure on them will help broaden my understanding of both my major and real estate as a whole.",
    experience: "",
  },
  {
    id: "caleb-paek", slug: "caleb-paek", name: "Caleb Paek",
    major: "Industrial Engineering - Analytics and Data Science", year: "Junior", grad: "Fall 2027", gradYear: 2027,
    disciplines: ["Brokerage/Investment Sales"],
    interests: "Brokerage attracts people who are analytical and relationship-driven. Brokerage is more about connecting capital, clients, and property value.",
    experience: "",
  },
  {
    id: "jonathan-pan", slug: "jonathan-pan", name: "Jonathan Pan",
    major: "Business Administration-IT Management, minor in computing & business through Denning T&M program", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development"],
    interests: "I am interested as there is land that is always needing to be developed. It is up to the contractors to make the decisions and understand what kinds of developments will reap the most reward.",
    experience: "Marketing Analytics Intern @ Delta Air Lines. Creating a data model and using it to power a tableau dashboard I designed and deployed during the 12 week internship. Incoming Spring 2026 Network Planning Co-op @ Delta Air Linea",
  },
  {
    id: "dev-patel", slug: "dev-patel", name: "Dev Patel",
    major: "Business Adminstration - Finance", year: "Freshman", grad: "May 2029", gradYear: 2029,
    disciplines: ["Capital Markets", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment", "Lending & Private Credit", "Brokerage/Investment Sales"],
    interests: "I want to understand different ways to invest in assets and find hidden gems where there is not development, and there is a high chance of development occuring.",
    experience: "",
  },
  {
    id: "aum-patel", slug: "aum-patel", name: "Aum Patel",
    major: "Business (finance concentration)", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Lending & Private Credit", "Brokerage/Investment Sales", "Property Management", "Real Estate Investment Trusts (REITs)", "Acquisitions", "Development"],
    interests: "I’m particularly interested in REITs and property management because they combine financial analysis with real, tangible assets. I like understanding how properties generate cash flow, how management decisions impact value, and how real estate can be structured as an investment vehicle. It’s appealing to see the direct link between strategy, operations, and financial performance.",
    experience: "",
  },
  {
    id: "rishi-patel", slug: "rishi-patel", name: "Rishi Patel",
    major: "Architecture", year: "Junior", grad: "Fall 2027", gradYear: 2027,
    disciplines: ["Development", "Construction", "Property Management"],
    interests: "Interested in understanding the relationship between developers, contractors, and architects in an effort to develop Atlanta.",
    experience: "",
  },
  {
    id: "pratham-patel", slug: "pratham-patel", name: "Pratham Patel",
    major: "Computer Science, Mod/Sim and Media", year: "Senior", grad: "Dec 2026", gradYear: 2026,
    disciplines: ["Foreign Investment", "Real Estate Investment Trusts (REITs)", "Property Management", "Construction", "Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development"],
    interests: "Lending and Private Credit seems the most interesting to me because just like the buyer the person financing also has vested interests in the property. They hope it is a good investment because they are interested in making their money back",
    experience: "I don't have any RE or finance internship experience but I have plenty of SWE internship experience",
  },
  {
    id: "arjunn-patel", slug: "arjunn-patel", name: "Arjunn Patel",
    major: "Business Administration, Undecided", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I really just want to learn as much as possible especially with things that have to do with the business realm.",
    experience: "",
  },
  {
    id: "svayam-patil", slug: "svayam-patil", name: "Svayam Patil",
    major: "Math major concentration in statistics and probability", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Development", "Brokerage/Investment Sales", "Lending & Private Credit", "Property Management"],
    interests: "I selected Development and Property Management because I have a natural passion for planning and organization, and I want to see how those skills apply to real estate.",
    experience: "",
  },
  {
    id: "sean-peck", slug: "sean-peck", name: "Sean Peck",
    major: "Business Administration, Finance, Minor in Computer Science", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Foreign Investment", "Property Management"],
    interests: "I have nothing in particular that I'm super passionate about, but I'm interested in learning about a couple of the disciplines and finding which one best suites me.",
    experience: "",
  },
  {
    id: "plern-pibuldham", slug: "plern-pibuldham", name: "Plern Pibuldham",
    major: "Civil Engineering", year: "Junior", grad: "May 2027", gradYear: 2027,
    disciplines: ["Development", "Construction", "Property Management", "Capital Markets", "Acquisitions"],
    interests: "I am currently a civil engineering major and I'm very interested in sustainable construction. I want to build buildings but I thought where should I build? So learning about real estate will help me learn about the disciplines I selected above!",
    experience: "This past summer I did an internship with Siemens as an Engineering Intern focused on construction and sustainability. Got a lot of behind the scenes experience such as analyzing and presenting energy data and calculating material costs. As for on site I got to learn about HVAC zoning and learned to confidently read floor plans. I wish I had more onsite experience because I was honestly on excel all the time but it was great experience!",
  },
  {
    id: "nicholas-poage", slug: "nicholas-poage", name: "Nicholas Poage",
    major: "Business, Minor in CS", year: "Sophomore", grad: "May 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Development"],
    interests: "Sounds very interesting and very useful to know ablut",
    experience: "Incoming Intern at Home Depot",
  },
  {
    id: "connor-prather", slug: "connor-prather", name: "Connor Prather",
    major: "Economics", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Construction", "Capital Markets"],
    interests: "I'm especially interested in desiging projects and analyzing the market to see what is most feasible",
    experience: "Worked under a local real estate development company last summer. Got experience filling out zoning forms and looking at development possibilities. Also met in person with government officials to discuss development plans.",
  },
  {
    id: "liam-puckhaber", slug: "liam-puckhaber", name: "Liam Puckhaber",
    major: "Business Administration", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Brokerage/Investment Sales", "Development"],
    interests: "I am very interested in brokerage",
    experience: "",
  },
  {
    id: "josseline-reyes-bravo", slug: "josseline-reyes-bravo", name: "Josseline Reyes-Bravo",
    major: "Majoring in Architecture", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Construction", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "The concept of real estate making me money is interesting to me.",
    experience: "",
  },
  {
    id: "benjamin-reznikov", slug: "benjamin-reznikov", name: "Benjamin Reznikov",
    major: "Computer Science", year: "Sophomore", grad: "May 2027", gradYear: 2027,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Brokerage/Investment Sales"],
    interests: "I am particularly interested in residential (both single and multi-family) investment properties and syndications as a way of semi-passive income. Thus, I am interested in property management and REITs (although I know a lot less about the latter). I'm also willing to learn about other parts of real estate to increase my knowledge and intuition.",
    experience: "I worked as a Research and Development Spectral Science Intern at the National Geospatial-Intelligence Agency summer of 2024. I am also currently a Student Research Assistant at the Georgia Tech Research Institute (GTRI) where I am primarily working with LIDAR data. Neither of these internships are related to real estate or finance however.",
  },
  {
    id: "devyn-rosenberg", slug: "devyn-rosenberg", name: "Devyn Rosenberg",
    major: "Business Administration, Finance", year: "Junior", grad: "Spring 27", gradYear: 0,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Capital Markets", "Development"],
    interests: "I am interested in development because construction loans are an important part of understanding the lifecycle of a project. I am also interested in acquisitions because I want to understand what makes certain properties attractive to lenders. Similarly, I am interested in capital markets because I want to learn about how economic trends and interest rates dictate deals. Finally, I am interested in lending and private credit because I want to improve and learn more about the quantitative side of commercial real estate.",
    experience: "Accounting Intern at Cents of Mind, Interned under the Practice Manager of Phoenix Ortho Injury Spine &Extremity, current marketing intern at Warner Bros. during school, expected internship next summer is at Greystone in Multifamily Lending",
  },
  {
    id: "jocelyn-santos-reyes", slug: "jocelyn-santos-reyes", name: "Jocelyn Santos-Reyes",
    major: "M.S with a major in Management", year: "Full-Time Graduate Student", grad: "Spring 2026", gradYear: 2026,
    disciplines: ["Development", "Construction", "Property Management", "Acquisitions"],
    interests: "I am more or so interested in the acquisition, development, and sales process of Real Estate. Therefore, my interests align with the development, acquisitions, construction, and property management fields.",
    experience: "I have interned as a real estate analyst in the past with Waffle House. This entailed finding suitable sites, doing due diligence, communicating with land owner to begin negotiations, and present findings to the head of the Real Estate department.",
  },
  {
    id: "abhishek-sekhar", slug: "abhishek-sekhar", name: "Abhishek Sekhar",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I’m interested in those particular fields because I’m much more of an analytical person, being better at working with numbers, and that’s a big part of real estate especially that side of real estate",
    experience: "I have internship experience more in CS when I interned my junior year in HS at an AI startup where we developed a program that would help tutor kids for the SAT using their specific learning styles",
  },
  {
    id: "steve-self", slug: "steve-self", name: "Steve self",
    major: "Business, accounting", year: "Part-Time Graduate Student", grad: "6/28", gradYear: 0,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    interests: "Real estate transactions",
    experience: "",
  },
  {
    id: "saajan-shah", slug: "saajan-shah", name: "Saajan Shah",
    major: "IE, Econ and Finance, Minor in Fintech", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Brokerage/Investment Sales", "Foreign Investment", "Construction", "Development"],
    interests: "I developed an early passion for real estate by growing up around the hotel industry with my grandparents, where I was exposed to the operational and development side of hospitality assets. More recently, my dad introduced me to the investment side of the industry, specifically low-income housing, short-term rentals, and large, complex real estate deals. These experiences sparked my interest in development, acquisitions, investment sales, lending/private credit, construction, and foreign investment, as I’ve seen firsthand how each discipline plays a crucial role in creating value and shaping communities. Looking ahead, I hope to build on what I’ve learned from my family but also add my own spin by exploring different asset classes, creative deal structures, and emerging markets both domestically and internationally. I want to combine traditional strategies with innovative approaches to find new opportunities, scale investments, and ultimately create a more modern, diversified real estate platform.",
    experience: "Product Engineering Intern at IHG Summer 2025",
  },
  {
    id: "abhishek-shahane", slug: "abhishek-shahane", name: "Abhishek Shahane",
    major: "Industrial Engineering", year: "Freshman", grad: "Dec 2028", gradYear: 2028,
    disciplines: ["Not sure"],
    interests: "I'm not sure yet, I'll have to wait and see what interests me.",
    experience: "I had a consulting internship with the city of Marietta, where with a team, I came up with a solution for fast and efficient business permits.",
  },
  {
    id: "asa-benjamin-winter-shitey", slug: "asa-benjamin-winter-shitey", name: "Asa Benjamin Winter Shitey",
    major: "Computer Engineering", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Acquisitions", "Property Management", "Real Estate Investment Trusts (REITs)", "Lending & Private Credit"],
    interests: "I want to use develop and rent out properties in my hometown.",
    experience: "",
  },
  {
    id: "leonid-shteynblik", slug: "leonid-shteynblik", name: "Leonid Shteynblik",
    major: "CIVIL ENGINEERING", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Capital Markets", "Brokerage/Investment Sales", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Acquisitions"],
    interests: "I really enjoy construction, development, and financial modeling and hope to be able to gain the skills needed to run my own firm eventually.",
    experience: "Fuentes Construction, heavy civil engineering firm focused on foundations, sheet piles, and maritime construction.",
  },
  {
    id: "monish-soniminde", slug: "monish-soniminde", name: "Monish Soniminde",
    major: "Economics, Minor in AIML, Minor in T&M", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Lending & Private Credit", "Development", "Real Estate Investment Trusts (REITs)", "Property Management"],
    interests: "I am interested in working in an acquisition based role but also in development and management as these acquisitions will require the latter.",
    experience: "Wealth Management Intern @ UBS",
  },
  {
    id: "kathleen-spaniol", slug: "kathleen-spaniol", name: "Kathleen Spaniol",
    major: "Business Administration, no concentration as of now", year: "Freshman", grad: "Spring 2030", gradYear: 2030,
    disciplines: ["Capital Markets", "Acquisitions", "Development", "Lending & Private Credit", "Foreign Investment", "Property Management"],
    interests: "Don’t know much about real estate, would love to learn about it through this club",
    experience: "",
  },
  {
    id: "adam-stadelmeier", slug: "adam-stadelmeier", name: "Adam Stadelmeier",
    major: "Business Administration, Finance", year: "Sophomore", grad: "Fall 2027 or Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment", "Brokerage/Investment Sales"],
    interests: "I have a strong passion for entrepreneurship and want to gain the skills needed to start my own real estate investment firm",
    experience: "The Whiting Turner Contracting Company, Summer 2025 ; Co Founder CraftPost LLC",
  },
  {
    id: "marcin-stryjecki", slug: "marcin-stryjecki", name: "Marcin Stryjecki",
    major: "MBA", year: "Full-Time Graduate Student", grad: "May 2027", gradYear: 2027,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    interests: "I am interested in the Finance side",
    experience: "I am in my 1st year",
  },
  {
    id: "ashrita-sunkara", slug: "ashrita-sunkara", name: "Ashrita Sunkara",
    major: "Indsutrial Engineering, Economic and Financial Systems", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Acquisitions", "Development", "Lending & Private Credit", "Property Management"],
    interests: "Since I want to get into the finance industry, I want to learn about the financial aspect of real estate. Moreover, I want to learn more about financial markets and investments.",
    experience: "Since I am a first-year student, I do not have any internship experience at a college level. However I have completed a Human Resources Internship with Forsyth County Schools and a Social Media/Marketing Internship with Heat Dance Academy. My HR internship taught me how to organize a team, enhance worker efficiency, and customer service skills. My internship at Heat Dance Academy taught me teamwork skills and how to graphically design content.",
  },
  {
    id: "satvik-tadiparthi", slug: "satvik-tadiparthi", name: "Satvik Tadiparthi",
    major: "Architecture", year: "Junior", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Construction", "Property Management"],
    interests: "I’m very interested in residential development and I feel that these disciplines will have a great impact on how I understand opportunities.",
    experience: "Architectural Design Intern at GPD Group, Construction Intern at BLK Constructions",
  },
  {
    id: "manuel-terrero", slug: "manuel-terrero", name: "Manuel Terrero",
    major: "MBA - Concentration: Undecided", year: "Evening Graduate Student", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Acquisitions", "Brokerage/Investment Sales", "Construction", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I’m especially interested in how real estate strategy supports media companies and themed entertainment brands, where creative storytelling and large-scale development intersect.",
    experience: "",
  },
  {
    id: "david-thompson", slug: "david-thompson", name: "David Thompson",
    major: "Business Administration, Finance Concentration", year: "Freshman", grad: "May 2030", gradYear: 2030,
    disciplines: ["Development", "Capital Markets", "Acquisitions", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Foreign Investment"],
    interests: "Finance/Private Equity/Asset Management",
    experience: "",
  },
  {
    id: "nk-thompson", slug: "nk-thompson", name: "NK Thompson",
    major: "Civil Engineering with a construction concentration", year: "Freshman", grad: "3031", gradYear: 0,
    disciplines: ["Development", "Construction", "Property Management", "Real Estate Investment Trusts (REITs)"],
    interests: "I want to go into construction management. I want to ensure buildings are constructed properly and look over the site. I also have an interest in selling houses I engineering/oversought if made by the city",
    experience: "",
  },
  {
    id: "alex-udoudoh", slug: "alex-udoudoh", name: "Alex Udoudoh",
    major: "Civil Engineering", year: "Freshman", grad: "May 2030", gradYear: 2030,
    disciplines: ["Property Management", "Construction", "Development"],
    interests: "Would like to look at the civil engineering side of real estate and looking into creating another stream of revenue.",
    experience: "I have interned with American Medical Response for a summer",
  },
  {
    id: "patrick-vettickatt", slug: "patrick-vettickatt", name: "Patrick Vettickatt",
    major: "Industrial Engineering", year: "Sophomore", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Lending & Private Credit", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions"],
    interests: "I am really interested in seeing how we can apply the math and science we learn as an industrial engineer into making financial decisions. Especially modeling, statistics, and programming and how it can be applied to finance.",
    experience: "GE Vernova - Process Improvement Intern, Upcoming 2026 Summer Walmart Process Quality Engineer Intern",
  },
  {
    id: "avery-watts", slug: "avery-watts", name: "Avery Watts",
    major: "Industrial Engineering", year: "Sophomore", grad: "Spring 2027", gradYear: 2027,
    disciplines: ["Development", "Acquisitions", "Capital Markets", "Brokerage/Investment Sales", "Lending & Private Credit", "Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment"],
    interests: "I am an Industrial Engineer, with a concentration in Financial and Economic Systems, so I'm particularly interested in optimizing prices, places, and systems. I have recently been working towards my real estate knowledge, so I have a baseline understanding of many real estate topics. However, I am naturally a curious person, so I am always looking for ways to learn more, especially when the topics interest me.",
    experience: "",
  },
  {
    id: "mason-williams", slug: "mason-williams", name: "Mason Williams",
    major: "Business Administration - Finance", year: "Sophomore", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Development", "Property Management", "Acquisitions"],
    interests: "I'm interested in learning the flow of money through acquisition as well as during development.",
    experience: "",
  },
  {
    id: "allison-wong", slug: "allison-wong", name: "Allison Wong",
    major: "Industrial Engineering", year: "Freshman", grad: "Spring 2028", gradYear: 2028,
    disciplines: ["Acquisitions", "Capital Markets", "Brokerage/Investment Sales"],
    interests: "With acquisitions, I can analyze various opportunities and weight the pros and the cons. With capital markets, I really enjoy economics and seeing how everything fits together to create a financial system. With brokerage/investment sales, I get to work on my sales skills.",
    experience: "",
  },
  {
    id: "jisang-yoon", slug: "jisang-yoon", name: "Jisang Yoon",
    major: "Aerospace Engineering", year: "Freshman", grad: "Spring 2029", gradYear: 2029,
    disciplines: ["Real Estate Investment Trusts (REITs)", "Property Management", "Foreign Investment", "Brokerage/Investment Sales", "Capital Markets", "Acquisitions", "Development", "Lending & Private Credit", "Construction"],
    interests: "Property management",
    experience: "",
  },
];

export const MEMBER_DISCIPLINES = Array.from(new Set(MEMBERS.flatMap((m) => m.disciplines))).sort();
export const MEMBER_GRAD_YEARS = Array.from(new Set(MEMBERS.map((m) => m.gradYear).filter(Boolean))).sort();

export function memberInitials(name: string): string {
  return name.split(' ').filter(Boolean).map((p) => p[0]).slice(0, 2).join('').toUpperCase();
}
